version: 2.1

defaults: &defaults
  docker:
    - image: circleci/clojure:tools-deps-1.10.0.411

orbs:
  cache: compute/cache@0.0.3

jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - cache/clj:
          steps:
            - run: clojure -A:test:test-runner

workflows:
  version: 2
  ci-workflow:
    jobs:
      - test